# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4dbad54c9f3c1389997728d9b99261fdc911824d99bb02ef244757c1680e4c92c5b544cbb2b4911fc2bda098bf6e13135a5fa4dc4a4ef5bad36ec77ad080170f

test:
  secret_key_base: fe3a81d1563fa2933edf2387292a54aef8ff0bd254f5825da8bb5f6688acbb7f813ef99b7046fcd91c3ab2f7d2c974c800fe1860b17631a7f1651f2e45dadf3b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
